import {IUser} from "../models/user";

export const users: object[] = [
  {
    "DistenceFromWork": 289,
    "city": "Rishon Le Zion",
    "dateOfBirth": "1996-04-28T21:00:00.000Z",
    "email": "refaelasraf@gmail.com",
    "netoIncome": 7855,
    "numOfPersonsToTakeCareOf": 4.08,
    "numOfProviders": 0.91,
    "password": "refaelAdmin",
    "socialCarePayment": 1805,
    "studyYears": 12.7,
    "taxesPayment": 78,
    "userName": "refaelAdmin",
    "_id" : 1,
    "groupId" : -1,
    "id" : null,
    "isAdmin" : true
  },
  {
    "DistenceFromWork": 3,
    "city": "Tel Aviv",
    "dateOfBirth": "1996-09-13T21:00:00.000Z",
    "email": "guyHalevyf@gmail.com",
    "netoIncome": 13300,
    "numOfPersonsToTakeCareOf": 3.45,
    "numOfProviders": 1.44,
    "password": "guyAdmin",
    "socialCarePayment": 1783,
    "studyYears": 13.2,
    "taxesPayment": 396,
    "userName": "guyAdmin",
    "_id" : 2,
    "groupId" : -1,
    "id" : null,
    "isAdmin" : true
  },
  {
    "DistenceFromWork": 2,
    "city": "Tel Aviv",
    "dateOfBirth": "1996-09-13T21:00:00.000Z",
    "email": "meiravns@gmail.com",
    "netoIncome": 18086,
    "numOfPersonsToTakeCareOf": 3.22,
    "numOfProviders": 1.67,
    "password": "meiravAdmin",
    "socialCarePayment": 1618,
    "studyYears": 13.8,
    "taxesPayment": 989,
    "userName": "meiravAdmin",
    "_id" : 3,
    "groupId" : -1,
    "id" : null,
    "isAdmin" : true
  },
  {
    "DistenceFromWork": "123",
    "city": "Givatiim",
    "dateOfBirth": "1995-09-13T21:00:00.000Z",
    "email": "tomas@gmail.com",
    "netoIncome": 23744,
    "numOfPersonsToTakeCareOf": 3.07,
    "numOfProviders": 1.76,
    "password": "tomAdmin",
    "socialCarePayment": 1618,
    "studyYears": 14.5,
    "taxesPayment": 2270,
    "userName": "tomAdmin",
    "_id" : 4,
    "groupId" : -1,
    "id" : null,
    "isAdmin" : true
  },
  {
    "DistenceFromWork": 12,
    "city": "hod hasharon",
    "dateOfBirth": "1996-09-13T21:00:00.000Z",
    "email": "etsionohad@gmail.com",
    "netoIncome": 35589,
    "numOfPersonsToTakeCareOf": 2.69,
    "numOfProviders": 1.74,
    "password": "ohadAdmin",
    "socialCarePayment": 1598,
    "studyYears": 15.6,
    "taxesPayment": 6903,
    "userName": "ohadAdmin",
    "_id" : 5,
    "groupId" : -1,
    "id" : null,
    "isAdmin" : true
  }
]